# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
   
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Setup node
      uses: actions/setup-node@v1
      with:
          node-version: 10
    
    # Install pandoc
    - name: Install pandoc
      run: sudo apt-get install -yqq --no-install-recommends pandoc

    # Runs a single command using the runners shell
    - name: Install pyton dependencies
      run: make install_dev_python_modules_verbose
    
    - name: Build docs
      run: |
        cd docs
        make buildnext
        cd docs
        yarn build
        yarn export
        
    - name: Deploy to surge
      run: |
        npm install -g surge
        surge ./docs/next/out ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
